name: Flutter

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - name: Format, Analyze, and Build
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.0.3"
                  channel: "stable"
                  cache: true
                  cache-key: flutter
            - run: flutter pub get
            - run: flutter format --output=none --set-exit-if-changed .
            - run: flutter analyze
            - run: flutter build
