name: Server

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [16.x, 17.x, 18.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: cd server && yarn install

            - name: Build
              run: cd server && yarn build
